version: "3"
services:
  php:
    image: php-apache
    build:
      context: .
    ports:
      - "8000:80"
      - "2222:22"
    volumes:
      - ./www:/var/www/html
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    depends_on:
      - db
    ports:
      - "8080:80"
